CREATE TABLE IF NOT EXISTS users(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(120) NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    password CHAR(20) NOT NULL CHECK(CHAR_LENGTH(TRIM(password)) > 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);